### Arrays en NumPy

In [4]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [5]:
vector = np.array([30, 29, 35, 31, 33, 36, 42])
print(vector)

[30 29 35 31 33 36 42]


In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
tensor = np.array([[[1, 2], [3,4], [5,6], [7,8]]])
print(tensor)


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [12]:
array_arrange = np.arange(10)
print(array_arrange)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [16]:
diag_matrix = np.diag([1, 2, 3, 4, 5, 6, 7])
print(diag_matrix)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [29]:
random = np.random.random((2,3))
print(random)

[[0.24304503 0.40777705 0.31906607]
 [0.60173504 0.0583048  0.42594819]]
