# 9 Cálculos Matriciales

In [1]:
import numpy as np

## Suma de Matrices

$$
\mathbf{A} + \mathbf{B} = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix} + \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix} = \begin{bmatrix} a_{11}+b_{11} & a_{12}+b_{12} \\ a_{21}+b_{21} & a_{22}+b_{22} \end{bmatrix}
$$

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Suma de matrices: A + B
suma = A + B

print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nA + B =")
print(suma)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


## Multiplicación de Matrices

$$
\mathbf{A} \cdot \mathbf{B} = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix} \cdot \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix} = \begin{bmatrix} a_{11}b_{11}+a_{12}b_{21} & a_{11}b_{12}+a_{12}b_{22} \\ a_{21}b_{11}+a_{22}b_{21} & a_{21}b_{12}+a_{22}b_{22} \end{bmatrix}
$$

In [4]:
# Multiplicación de matrices: A · B
producto = np.dot(A, B)

print("A · B =")
print(producto)

[[19 22]
 [43 50]]


## Determinante e Inversa

**Determinante** (notación con barras verticales):

$$
|\mathbf{A}| = \begin{vmatrix} a & b \\ c & d \end{vmatrix} = ad - bc
$$

**Matriz Inversa**:

$$
\mathbf{A}^{-1} = \frac{1}{|\mathbf{A}|} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

*Propiedad:* $\mathbf{A} \cdot \mathbf{A}^{-1} = \mathbf{I}$ (matriz identidad)

In [7]:
# Determinante e Inversa de una matriz
A = np.array([[1, 2], [3, 4]])

# Determinante: det(A) = (1*4) - (2*3) = -2
det_A = np.linalg.det(A)

# Matriz inversa: A * A⁻¹ = I (identidad)
inv_A = np.linalg.inv(A)

print("Matriz A:")
print(A)
print(f"\nDeterminante de A: {det_A:.2f}")
print("\nInversa de A:")
print(inv_A)
print("\nVerificación (A @ A⁻¹ = Identidad):")
print(np.round(A @ inv_A))

Matriz A:
[[1 2]
 [3 4]]

Determinante de A: -2.00

Inversa de A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Verificación (A @ A⁻¹ = Identidad):
[[1. 0.]
 [0. 1.]]


## Resolución de Sistema de Ecuaciones Lineales

$$
\mathbf{A}\vec{x} = \vec{b}
$$

Donde:
- $\mathbf{A}$ = matriz de coeficientes
- $\vec{x}$ = vector de incógnitas
- $\vec{b}$ = vector de términos independientes

**Solución:**

$$
\vec{x} = \mathbf{A}^{-1} \vec{b}
$$

En nuestro caso:

$$
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} 9 \\ 11 \end{bmatrix}
$$

In [8]:
# Resolver A⃗x = b⃗
b = np.array([9, 11])
x = np.linalg.solve(A, b)

print("Vector b⃗:", b)
print(f"\nSolución x⃗: {x}")
print(f"  x₁ = {x[0]}")
print(f"  x₂ = {x[1]}")
print(f"\nVerificación (A · x⃗ = b⃗): {A @ x}")

Vector b⃗: [ 9 11]

Solución x⃗: [-7.  8.]
  x₁ = -7.0
  x₂ = 8.0

Verificación (A · x⃗ = b⃗): [ 9. 11.]
